-- === Phase 2.E — Cron weekly: scrape-commercial-facts ===
-- Cf. backlog #2.7 et #5.3.
-- Schedule: Monday 08:00 UTC. Calls scrape-commercial-facts which reads
-- tenant_config.website_url, walks the footer/nav links, and refreshes
-- tenant_commercial_facts via Gemini Flash extraction.
--
-- IMPORTANT for the onboarding runbook: the URL hardcoded below points to
-- the template's project_ref (btkjdqelvvqmtguhhkdv). Each new tenant has a
-- distinct Supabase project and must update this URL + JWT (anon key)
-- after the migration is replayed in their project. Same convention as the
-- existing weekly-intelligence-refresh cron.
--
-- pg_cron and pg_net extensions are already enabled by earlier migrations
-- (20260219005453, 20260329104714) so no extension setup is needed here.

-- NEUTRALIZED: cron.schedule commented out because it hardcodes the template
-- project_ref (btkjdqelvvqmtguhhkdv). Crons must be created per-tenant via
-- a dedicated idempotent migration with dynamic URL resolution.
-- See: docs/RUNBOOK_ONBOARDING_CLIENT.md §4
